### ISSUE TITLE
ReCaptcha_solver.iim not working, ERROR_GOOGLEKEY

### ISSUE THREAD

**Issue by Baldoius** [2captcha/2captcha-api-examples#1]
The provided file ReCaptcha_solver.iim isn't working.
Response from your API: ERROR_GOOGLEKEY

**Comment by 2captcha** [comment]
Здравствуйте. Видимо шлете не правильный домен в параметре pageurl10.11.2016, 00:56, "Dario Ackermann" <notifications@github.com>:The provided file ReCaptcha_solver.iim isn't working.
Response from your API: ERROR_GOOGLEKEY

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




-- С уважением,всегда на связиТех.Поддержка RuCaptcha.com

**Comment by 2captcha** [comment]
Hi,
Have you correctly inserted your googlekey?
THanks.

**Comment by 2captcha** [comment]
@Baldoius does the issue still persist?

**Comment by Baldoius** [comment]
Yes. I do provide it correctly.

**Comment by 2captcha** [comment]
Could you please submit a ticket from our FAQ section: https://2captcha.com/support/faq/15/
I'll check your account.

**Comment by Baldoius** [comment]
Hey.
It's the script. I've written my own userscript which is working.
Can you (after reading) delete this and contact me then?

**Comment by 2captcha** [comment]
Hi,
You are doing something wrong as we have tested at: 
https://www.google.com/recaptcha/api2/demo and 1-2 more websites right now.
you should replace KEY and submit button.
Thanks.
