### ISSUE TITLE
Javascript API error

### ISSUE THREAD

**Issue by AssHole12** [2captcha/2captcha-api-examples#3]
When I use the Javascript API, I get SyntaxError: Unexpected token, expected ; (44:14)

Can you please fix this?

**Comment by 2captcha** [comment]
Hi @AssHole12 !
Could you please show the exact file where you met the error?

**Comment by AssHole12** [comment]
@2captcha https://github.com/2captcha/2captcha-api-examples/blob/master/ReCaptcha%20v2%20API%20Examples/JavaScript%20Example/javascript%20api.js 
I get error Uncaught SyntaxError: Unexpected identifier

**Comment by 2captcha** [comment]
Hello we are not developers - please try appropriate forums or consider hiring a specialist.24.04.2017, 18:33, "AssHole12" <notifications@github.com>:@2captcha https://github.com/2captcha/2captcha-api-examples/blob/master/ReCaptcha%20v2%20API%20Examples/JavaScript%20Example/javascript%20api.js
I get error Uncaught SyntaxError: Unexpected identifier

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




Dear customer,   --Thanks,2captcha.com support.
